### PR TITLE
Fix filtering by local labels

### LINKED ISSUE #2008: With Data Collection turned off, masks cannot be searched on the dashboard by their label/name

### PR DESCRIPTION
**Pull request by Vinnl**
This PR fixes #2008. We used to apply the locally-stored labels to the mask data *after*
applying the filter. This flips that around.

How to test: disable server-side label storage. Add labels with the extension, then enter that label in the search field. (Make sure to run on 127.0.0.1, so that the extension becomes active.) As follows:

https://user-images.githubusercontent.com/4251/171151940-670520b0-82ff-42cd-8f2a-831459fd7012.mp4

I also fixed the one warning we used to get when running the front-end tests about updating an unmounted component in 5d481203ee895da3589067abf0d0384659c9999c.

- [x] l10n changes have been submitted to the l10n repository, if any.
- [x] I've added a unit test to test for potential regressions of this bug.
- [x] I've added or updated relevant docs in the docs/ directory.
- [x] All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/static/scss/libs/protocol/css/includes/tokens/dist/index.scss`).
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

### CODE REVIEW

File: frontend/src/components/dashboard/aliases/LabelEditor.tsx [hunk 1]
```diff
@@ -29,7 +29,8 @@ export const LabelEditor = (props: Props) => {
 
   useEffect(() => {
     setLabelJustUpdated(true);
-    setTimeout(() => setLabelJustUpdated(false), 1000);
+    const updateTimeout = setTimeout(() => setLabelJustUpdated(false), 1000);
+    return () => clearTimeout(updateTimeout);
```
Comment (lloan) [inline frontend/src/components/dashboard/aliases/LabelEditor.tsx:33]: question (non-blocking): For sake of learning on my part, why do you set a timeout for this cleanup function?

**Review by lloan — APPROVED** [review]
LGTM. Left a non-blocking question.

File: frontend/src/components/dashboard/aliases/LabelEditor.tsx (hunk 1 above)
Comment (Vinnl) [reply frontend/src/components/dashboard/aliases/LabelEditor.tsx:33]: The timeout was already there, to hide the "Saved!" tooltip after a second passes. However, if the component gets unmounted before the timeout's callback executes (e.g. because the user navigates to another page within a second, or in tests), the `setLabelJustUpdated` call no longer makes sense. Thus, the change here is to drop that timeout as soon as the component unmounts.

image
