### PR TITLE
Clickable label for the "Block Promotional emails" track stop

### LINKED ISSUE #2033: For a free user, clicking on the title below the “Promotionals” status bubble does not show its educational modal
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, Release version;
- Chrome, Release version;

#### Prerequisites:
- Be signed in into a Free Firefox Relay account;
- Have at least one mask created;

#### Steps to reproduce:
1. Go to the Relay dashboard;
2. Expand one of the generated masks;
3. Click on the title below the “Promotionals” status bubble;

#### Expected result:
- Clicking on the title opens the educational modal;

#### Actual result:
- Clicking on the title doesn’t open the educational modal;

#### Notes:
- The “All” and “None” status bubbles work as expected, in the sense that clicking on their titles activates their bubbles;
- The only way to make the educational modal show up is to click on the “Promotionals” bubble;
- See attached media:
bubble

### LINKED ISSUE #2045: Premium user has issues setting masks to the “Promotionals” status
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, Release version;
- Chrome, Release version;

#### Prerequisites:
- Be signed in into a Premium Firefox Relay account;
- Have a Subdomain set;

#### Steps to reproduce:
1. Go to the Relay dashboard;
2. Generate a new Random mask and a new Custom Subdomain mask;
3. In the open cards of the two freshly generated masks, switch their statuses to “Promotionals”;
4. Continue switching between the statuses;
5. Observe the results;

#### Expected result:
- The masks have no issues switching through the statuses;

#### Actual result:
- Sometimes the masks do not switch to the “Promotionals” status;

#### Notes:
- This issue is constant, but sometimes switching to the “Promotionals” status successfully. From what I’ve seen this may happen when switching faster than usual;
- See attached media:
switch

### PR DESCRIPTION
**Pull request by Vinnl**
This PR fixes #2033 and fixes #2045.

To look like a regular track stop, the ghost button was resized to
the small circle of a track stop, with the label displayed outside
of it. However, that meant that only that small circle was the
actual, clickable button.

Now, I added a <span> that looks like the track stop, and made the
button span a full one-third of the slider, and the same height, so
that it can fully encompass both the track stop and its label.

I also limited what's now called the `<PromotionalTrackStopGhost>` to only be shown for free users, where it has the weird behaviour of not actually being part of the slider and having a tooltip show up when it's clicked. For Premium users, Promo-blocking now has a regular track stop again, just like blocking nothing or everything.

How to test: for Premium users, promo-blocking should keep working exactly the same as blocking nothing or everything. For free users, you should now be able to click the word "Promotionals" just like the circle above it to activate the popup.

- [x] l10n changes have been submitted to the l10n repository, if any.
- [ ] I've added a unit test to test for potential regressions of this bug. N/A - no business logic.
- [x] I've added or updated relevant docs in the docs/ directory.
- [x] All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/static/scss/libs/protocol/css/includes/tokens/dist/index.scss`).
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

### CODE REVIEW

File: frontend/src/components/dashboard/aliases/BlockLevelSlider.tsx [hunk 1]
```diff
@@ -116,6 +116,26 @@ export const BlockLevelSlider = (props: Props) => {
               <img src={UmbrellaClosedMobile.src} alt="" />
               <p aria-hidden="true">{getLabelForBlockLevel("none", l10n)}</p>
             </div>
+            {/*
+              Onlt show the "Promotionals" track stop to Premium users.
```
Comment (lloan) [inline frontend/src/components/dashboard/aliases/BlockLevelSlider.tsx:120]:
```suggestion
              Only show the "Promotionals" track stop to Premium users.
```

**Review by lloan — APPROVED** [review]
Overall, this looks good. 

I did have a question about this (video attached).

Clicking from one to the next gets stuck sometimes. You can click outside the component and it then allows you to click `promotionals`. Not sure if it has anything to do with this PR but figured I'd mention it to you.

https://user-images.githubusercontent.com/3924990/173468530-f025b03a-84f9-47f1-9ed0-43464dde8452.mp4

**Comment by Vinnl** [comment]
Thanks @lloan, that looks like #2045, which this PR is supposed to fix :/ However, looking at the URL in the browser in your video, it looks like you might have had the demo site for a different PR open? Could you verify if you can still reproduce that in https://deploy-preview-2077--fx-relay-demo.netlify.app/accounts/profile/?mockId=full? Because I can't...

**Comment by lloan** [comment]
> Thanks @lloan, that looks like #2045, which this PR is supposed to fix :/ However, looking at the URL in the browser in your video, it looks like you might have had the demo site for a different PR open? Could you verify if you can still reproduce that in https://deploy-preview-2077--fx-relay-demo.netlify.app/accounts/profile/?mockId=full? Because I can't...

You are 100% correct - I just checked using the correct pull # on Netlify and it works perfectly.

**Comment by Vinnl** [comment]
Awesome, thanks for checking!
