### PR TITLE
Apply search and category filters together

### LINKED ISSUE #950: Uncaught TypeError: can't access property "addEventListener", filterToggleSearchInput is null
STR:
1. Go to https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/ with no aliases

Expected results:
no errors

Actual results:
```
Uncaught TypeError: can't access property "addEventListener", filterToggleSearchInput is null
    <anonymous> https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/static/js/filter.js:26
    <anonymous> https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/static/js/filter.js:130
filter.js:26:5
    <anonymous> https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/static/js/filter.js:26
    <anonymous> https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/static/js/filter.js:130
```

### LINKED ISSUE #1055: After search filters have been applied, unchecking all filters and clicking "Apply" doesn’t do anything
#### Build:
- Stage;

#### Affected Platforms:
- Across platforms;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Be signed in into a Firefox Relay account with an active subscription;
- Have a few aliases created;
- Have some of the aliases’ forwarding disabled;

#### Steps to reproduce:
1. Go to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/ ;
2. Open the filters menu;
3. Check the “Active aliases” filter and click the “Apply” button;
4. Open the filters menu again;
5. Uncheck the “Active aliases” filter and click the “apply” button;

#### Expected result:
- Applying no filters should reset the filters and the alias list should be updated accordingly;

#### Actual result:
- Applying no filters does nothing and the aias list does not update;;

#### Notes:
- Even though there is a “Reset” button, the issue action seems counter-intuitive, and applying no filters feels like it should work the same as reset. Otherwise, the "Apply" button could become unclickable/inactive when no filter options are checked;
- This could be considered an enhancement;
apply no search filter

### LINKED ISSUE #1056: Filter issue when using the "x" button in the Search aliases bar
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit
macOS 10.14
Android 11
iOS 14.6

**Browsers tested on:**
Firefox

**Preconditions:**
The user has an active subscription.
The user has a few aliases added, some have forwarding enabled and some disabled.

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net and log in using an existing account. 
2. Click on the filter button and check Active aliases option.
3. Click Apply and observe the displayed results.
4. Click in the Search aliases bar and then click the "x" button.
5. Observe the displayed results.

**Actual result:**
Both enabled and disabled aliases are displayed although the Active aliases filter is ON.

**Expected result:**
Only the Active aliases are displayed.

filter issue

### LINKED ISSUE #1058: The “X” button from the “Alias search” bar can be clicked even if not visible
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10, Android 9;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Be signed in into a Firefox Relay account with an active subscription;
- Have a few aliases created;
- Have some of the aliases’ forwarding disabled;

#### Steps to reproduce:
1. Go to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/ ;
2. Open the filters menu;
3. Check the “Active aliases” filter and click the “Apply” button;
4. In the “Alias search” bar click towards the left end of the bar, where the “X” button usually is;
5. Observe the results;

#### Expected result:
- The “X” button should not be clickable if it’s not visible;

#### Actual result:
- The “X” button is clickable even if it is not visible;

#### Notes:
- N/A;
invisible X button

### LINKED ISSUE #1060: The filters break if using the “Alias search” bar together with the filters from the filter menu
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Be signed in into a Firefox Relay account with an active subscription;
- Have a few aliases created;
- Have some of the aliases’ forwarding disabled;

#### Steps to reproduce:
1. Go to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/ ;
2. In the “Alias search” bar, type a character or group of characters shared by two or more aliases ( “.” is a good example);
3. Open the filters menu and apply the “Enabled aliases” filter;
4. Open the filters menu and apply the “Disabled aliases” filter;
5. Observe the results;

#### Expected result:
- The filter should update accordingly, the alias list showing disabled aliases that contain “.” in their address;

#### Actual result:
- The filters break, the alias list showing none of the filters, and a filter reset doesn’t fix this issue;

#### Notes:
- It doesn’t happen only with the “.”, I have checked with aliases containing the same couple of characters;
filters breaking

### LINKED ISSUE #1064: “Emails Forwarded” number from the counter goes down if an alias is deleted
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10, Android 9;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Be signed in into a Firefox Relay account with an active subscription;
- Have a few aliases created;
- Have an alias that has forwarded a few emails;

#### Steps to reproduce:
1. Go to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/ ;
2. Observe the alias counter for “Emails Forwarded” at the top of the page;
3. Delete the alias that has forwarded a few emails;
4. Observe the alias counter again;

#### Expected result:
- The number of emails forwarded does not go down from deleting an alias;

#### Actual result:
- The number goes down;

#### Notes:
- [Link](https://mozilla-hub.atlassian.net/browse/MPP-783). "Accurately display for all of time how many emails have been forwarded to me through Relay. This number should not go down from deleting or disabling an account, this number should only go up.";
forwardcount

### PR DESCRIPTION
**Pull request by Vinnl**
Fixes #1060, fixes #1058, fixes #1056, fixes #1055, fixes #1064, fixes #950.

To fix these issues, I split the filter code in two parts: updating a model
containing the current filters (i.e. `activeWordFilter` and
`activeCategoryFilters`), and a function that reads that model and
iterates over all aliases currently present in the DOM and chooses
whether to display them based on that model. Hope you don't mind - I know it's not a great look to come in to an existing codebase and doing somewhat more extensive refactoring, but I didn't have a good enough grip on the code yet to reliably find all the places I'd have to make sure the two different types of filters (search and category) apply.

The goal of the refactoring is to make sure that filters can be updated independently, with the
resulting view always being consistent regardless of the order the
filters are applied in.

I also removed the duplicate administration of which aliases and
labels are currently available; instead, the `applyFilters`
function takes the DOM as the source of truth for available
aliases and labels. Ideally it would use the same data there as is
used for displaying those aliases in the first place, but that
would be a larger refactoring for which now is not the time.

### CODE REVIEW

File: static/js/filter.js [hunk 1]
```diff
@@ -1,430 +1,176 @@
...
-        
-        // Build two arrays, one for case IDs and one for case title text. 
-        const isCategoryFilterActive = (filterContainer.classList.contains("is-filtered-by-category"));
+    filterSearchInput.addEventListener("input", (event) => {
+        setSearchFilter(event.target.value);
+    });
 
-        let availableAliasesForSearchFilter = aliases;
+    // TODO: Add esc key listener
+    filterResetButton.addEventListener("click", (event) => {
```
Comment (maxxcrawford) [inline static/js/filter.js:81]: nit: unused event arg
```suggestion
    filterResetButton.addEventListener("click", () => {
```

File: static/js/filter.js [hunk 2]
```diff
@@ -1,430 +1,176 @@
...
+        setSearchFilter("");
+    });
 
-        if (isCategoryFilterActive) {
-            availableAliasesForSearchFilter = document.querySelectorAll(".c-alias:not(.is-hidden)");
+    filterToggleSearchInput.addEventListener("click", (event) => {
```
Comment (maxxcrawford) [inline static/js/filter.js:85]: nit: unused event arg
```suggestion
    filterToggleSearchInput.addEventListener("click", () => {
```

File: static/js/filter.js [hunk 3]
```diff
@@ -1,430 +1,176 @@
...
-        filterCategoryWrapper.classList.toggle("is-menu-open");
-
+    function closeCategoryMenu() {
+        filterToggleCategoryInput.classList.remove("is-enabled");
+        filterCategoryWrapper.classList.remove("is-menu-open");
+        document.removeEventListener("click", categoryMenuOpenListener, false);
+        document.removeEventListener("keydown", categoryMenuEscListener, false);
+    }
+    // TODO: Add "f" key listener to toggle category filter
+    filterToggleCategoryInput.addEventListener("click", (event) => {
```
Comment (maxxcrawford) [inline static/js/filter.js:126]: nit: unused event arg
```suggestion
    filterToggleCategoryInput.addEventListener("click", () => {
```

File: static/js/filter.js [hunk 4]
```diff
@@ -1,430 +1,176 @@
...
+    }
+    filterCategoryCheckboxes[0].form.addEventListener("submit", (event) => {
+        event.preventDefault();
+        const categoriesToSet = Array.from(filterCategoryCheckboxes)
+            .filter(checkbox => checkbox.checked)
+            .map(checkbox => checkbox.dataset.categoryType);
+        setCategoryFilters(categoriesToSet);
+        closeCategoryMenu();
+    });
+    filterCategoryCheckboxes[0].form.addEventListener("reset", (event) => {
```
Comment (maxxcrawford) [inline static/js/filter.js:146]: nit: unused event arg
```suggestion
    filterCategoryCheckboxes[0].form.addEventListener("reset", () => {
```

File: static/js/filter.js [hunk 5]
```diff
@@ -1,430 +1,176 @@
...
-            if (options.length < 1) {
+    function setCategoryFilters(categories) {
+        activeCategoryFilters = categories;
+        applyFilters();
+    }
+    filterCategoryCheckboxes[0].form.addEventListener("submit", (event) => {
+        event.preventDefault();
+        const categoriesToSet = Array.from(filterCategoryCheckboxes)
+            .filter(checkbox => checkbox.checked)
+            .map(checkbox => checkbox.dataset.categoryType);
```
Comment (maxxcrawford) [inline static/js/filter.js:142]: 🎉  Love how clean this logic is. Great rewrite!

File: static/js/filter.js [hunk 6]
```diff
@@ -1,430 +1,176 @@
...
-        if (newLabel === "") {
-            filterAliasLabels.splice(labelArrayIndex, 1);
-            aliasesWithLabelsCollection.splice(AliasWithLabelsArrayIndex, 1);
-            return;
+        if (activeSearchFilter.length > 0) {
+            filterSearchInput.classList.add("is-filtered");
+            filterContainer.classList.add("is-filtered-by-search");
+        } else {
+            filterSearchInput.classList.remove("is-filtered");
+            filterContainer.classList.remove("is-filtered-by-search");
```
Comment (maxxcrawford) [inline static/js/filter.js:61]: nit: add context comment on this use-case for this if statement 
```suggestion
        // Run if user has input a query into the search form
        if (activeSearchFilter.length > 0) {
            filterSearchInput.classList.add("is-filtered");
            filterContainer.classList.add("is-filtered-by-search");
        } else {
            filterSearchInput.classList.remove("is-filtered");
            filterContainer.classList.remove("is-filtered-by-search");
```

File: static/js/filter.js [hunk 7]
```diff
@@ -1,430 +1,176 @@
...
         }
-
-        // Case: User updated an existing label to a new string
-        if (labelArrayIndex > -1) {
-            filterAliasLabels.splice(labelArrayIndex, 1, newLabelLowercased);
-            return;
+        if (activeCategoryFilters.length > 0) {
+            filterContainer.classList.add("is-filtered-by-category");
+        } else {
+            filterContainer.classList.remove("is-filtered-by-category");
```
Comment (maxxcrawford) [inline static/js/filter.js:66]: nit: add context comment on this use-case for this if statement
```suggestion
        // // Run if user has a category filter active
        if (activeCategoryFilters.length > 0) {
            filterContainer.classList.add("is-filtered-by-category");
        } else {
            filterContainer.classList.remove("is-filtered-by-category");
```

**Review by maxxcrawford — APPROVED** [review]
@Vinnl This a fantastic rewrite that solves SIX issues at once, and only touches a single file. I have a few non-blocking nitpicks. Thanks for this contribution!

File: static/js/filter.js (hunk 1 above)
Comment (Vinnl) [reply static/js/filter.js]: Fixed in 19bf72a48b16d8c1408f2229478cb62040bbe1dc.

File: static/js/filter.js (hunk 3 above)
Comment (Vinnl) [reply static/js/filter.js]: Fixed in 19bf72a48b16d8c1408f2229478cb62040bbe1dc.

File: static/js/filter.js (hunk 4 above)
Comment (Vinnl) [reply static/js/filter.js]: Fixed in 19bf72a48b16d8c1408f2229478cb62040bbe1dc.

File: static/js/filter.js (hunk 2 above)
Comment (Vinnl) [reply static/js/filter.js]: Fixed in 19bf72a48b16d8c1408f2229478cb62040bbe1dc.

File: static/js/filter.js (hunk 6 above)
Comment (Vinnl) [reply static/js/filter.js:62]: Fixed in cfe92c0b7f7a272fb2c10feb32175c75cb9f5cd0.

File: static/js/filter.js (hunk 7 above)
Comment (Vinnl) [reply static/js/filter.js:68]: Fixed in cfe92c0b7f7a272fb2c10feb32175c75cb9f5cd0.
