### PR TITLE
Make the chosen domain fit in more situations

### LINKED ISSUE #1091: Alias domain not fully visible in the confirmation dialog
**Build:**
Stage

**Affected platforms:**
Windows 10 64 bit
macOS 10.14
Android 11
iOS 14.6

**Browsers tested on:**
Firefox

**Preconditions:**
The user has an active subscription but no email domain added.

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net and log in with an existing account.
2. Fill in the Search domain field and click the "Get Domain" button.
3. Observe the confirmation dialog.

**Actual result:**
The alias domain is not fully visible in the dialog.

**Expected result:**
The alias domain is fully visible in the dialog.

domain not fully visible in confirmationdialog

### PR DESCRIPTION
**Pull request by Vinnl**
Fixes #1091.

If the chosen domain is somewhat long, the suffix will be hidden
on small screens. If the suffix is very long, the suffix will
always be hidden, and the font size will be decreased on small
screens.

https://user-images.githubusercontent.com/4251/133632079-f069417e-6ac9-415c-be0a-467673d9de22.mp4

### CODE REVIEW

File: static/js/domain-registration.js [hunk 1]
```diff
@@ -76,17 +76,26 @@
                 modal.classList.add("is-visible");
 
                 const requestedDomain = document.querySelector(".js-subdomain-value");
-                const requestedDomainPreview = document.querySelectorAll(".js-modal-domain-registration-confirmation-domain-preview");
+                const requestedDomainPreview = document.querySelector(".js-modal-domain-registration-confirmation-domain-preview");
```
Comment (Vinnl) [inline static/js/domain-registration.js:79]: @maxxcrawford Any idea why this was a `querySelectorAll` instead of a `querySelector`? As far as I can see there's only one such element in the entire codebase.

Comment (maxxcrawford) [reply static/js/domain-registration.js:79]: It's in two locations, both in the `modal-domain-registration-confirmation.html` file: 
- https://github.com/mozilla/fx-private-relay/blob/main/privaterelay/templates/includes/modal-domain-registration-confirmation.html#L21
- https://github.com/mozilla/fx-private-relay/blob/main/privaterelay/templates/includes/modal-domain-registration-confirmation.html#L11

Per your demo video, it's here and here (the second instance is currently broken bc of the lack of the `querySelectorAll`) 

image

File: static/js/domain-registration.js [hunk 2]
```diff
@@ -76,17 +76,26 @@
...
                 const requestedDomainPreviewEnding = document.querySelector(".js-modal-domain-registration-confirmation-domain-ending")
                 
                 // Preview the domain the user requested
-                requestedDomainPreview.forEach( preview => {
-                    preview.textContent = requestedDomain.value;
-                })
```
Comment (maxxcrawford) [inline static/js/domain-registration.js:85]: Revert this change to restore that funcitonality (as called out in the [other comment](https://github.com/mozilla/fx-private-relay/pull/1109/files#r714451468)).

**Review by maxxcrawford — CHANGES_REQUESTED** [review]
This is a fantastic design solution for this. Thanks for handling all the dynamics here! 

I have a blocking change that I outlined below. Other than that, good to go!

File: static/js/domain-registration.js (hunk 2 above)
Comment (Vinnl) [reply static/js/domain-registration.js:85]: Haaa that was silly; I was looking for element accessors (`[0]`, `[1]`, etc.) and just mentally ignored this `forEach` :joy:  Fixed in c5dfbc1 (which I've rebased already to avoid accidental merges; hope that doesn't interfere with local checkouts.)

**Review by maxxcrawford — APPROVED** [review]
Awesome. Let's goooooo.
