### PR TITLE
List tracker blocking if Premium's unavailable

### LINKED ISSUE #2332: The price plans from the Landing and Interstitial pages do not list “Email tracker removal” to users from non-Premium countries
#### Build:
- Stage;

#### Affected Platforms:
- Across platforms;

#### Browsers tested on:
- Firefox, Release version;

#### Prerequisites:
- Do NOT be signed in into a Firefox Relay account;
- Have a VPN set to a country that doesn’t have Premium Relay available (e.g. Romania, Brazil);

#### Steps to reproduce:
1. Go to the Relay Landing page;
2. Scroll down to the price plans and observe their features;
3. Go to the Relay Interstitial page;
4. Scroll down to the price plans and observe their features;

#### Expected result:
- The price plans list “Email tracker removal” as a feature;

#### Actual result:
- The price plans do not list “Email tracker removal” as a feature;;

#### Notes:
- See attached media:
noremv1
image

### PR DESCRIPTION
**Pull request by Vinnl**
In countries were Relay Premium is not available, tracker blocking
would not be listed under the plans as an available feature. The
reason for this is that if Premium was not available, we weren't
even passing `runtimeData` to the `<Plans>` component (assuming
that it wouldn't be necessary if there were no plans to select).
However, that data is also needed to determine whether the flag is
active already.

This PR fixes #2332.

How to test: open the landing page and `/premium` with your browser language set to that of a country where Premium is unavailable (or, on stage, use a VPN). Tracker removal should be listed as a feature in the pricing plans cards:

image

- [x] l10n changes have been submitted to the l10n repository, if any.
- [ ] I've added a unit test to test for potential regressions of this bug. - Not sure if that makes sense here?
- [x] I've added or updated relevant docs in the docs/ directory.
- [x] All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/frontend/src/styles/tokens.scss`).
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

### CODE REVIEW

File: frontend/src/components/landing/Plans.tsx [hunk 1]
```diff
@@ -8,15 +8,15 @@ import {
...
 } from "../../functions/getPlan";
 import { trackPurchaseStart } from "../../functions/trackPurchase";
 import { getRuntimeConfig } from "../../config";
 import Link from "next/link";
 import { isFlagActive } from "../../functions/waffle";
+import { RuntimeData } from "../../hooks/api/runtimeData";
 
 export type Props = {
-  premiumCountriesData?: RuntimeDataWithPremiumAvailable;
+  runtimeData?: RuntimeData;
```
Comment (Vinnl) [inline frontend/src/components/landing/Plans.tsx:19]: Most of the lines changed are the rename from `premiumCountriesData` to `runtimeData`, and updating the type to just `RuntimeData` (rather than a type that indicates that we've already checked that Premium is available).

The actual fix, however, is in `index.page.ts` and `premium.page.ts`, where this prop is also added for the rendering of `<Plans>` in non-Premium countries.

**Review by lloan — APPROVED** [review]
Pretty straightforward changes - looks good to me.
