### PR TITLE
Restore the correct alias toggle tooltip

### LINKED ISSUE #1073: Enable/disable alias tooltip reverts to English after a click
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Be signed in into a Firefox Relay account;
- Have a few aliases created;
- Have the browser set to a supported language for Relay other than English (e.g.: German-de, French-fr);

#### Steps to reproduce:
1. Go to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/ ;
2. Scroll down to the alias list;
3. Hover on the enable/disable button of an alias and observe the tooltip;
4. Click on the enable/disable button and observe the tooltip;

#### Expected result:
- The tooltip has no translation issues;

#### Actual result:
- The tooltip reverts to English after a click;

#### Notes:
- Up until now it is present for all languages listed on the respective Pontoon project;
l10n dutch tooltip

### PR DESCRIPTION
**Pull request by Vinnl**
Fixes #1073.

### CODE REVIEW

File: static/js/app.js [hunk 1]
```diff
@@ -28,15 +28,18 @@ async function updateEmailForwardingPrefs(submitEvent) {
     const response = await sendForm(forwardingPrefForm.action, formData);
     if (response && response.status === 200) {
       prefToggle.classList.toggle("forwarding-disabled");
-      prefToggle.title = prefToggle.dataset.defaultTitle;
       if (prefToggle.value === "Enable") {
+        prefToggle.title = prefToggle.dataset.defaultBlockingTitle;
         toggleLabel.textContent = toggleLabel.dataset.defaultForwardingLabel;
         wrappingEmailCard.classList.add("is-enabled");
-        return prefToggle.value = "Disable";
```
Comment (Vinnl) [inline static/js/app.js:35]: It took me soooo long to figure this out, because I'd completely missed there was an assignment (`=`) in the return statement :cry:

**Review by maxxcrawford — APPROVED** [review]
🟢

File: static/js/app.js (hunk 1 above)
Comment (maxxcrawford) [reply static/js/app.js:35]: Oof. Glad you found it!
