### PR TITLE
fix #772: popup needs areInputIconsEnabled

### LINKED ISSUE #772: Setting "Show Relay icon in email fields on websites" does not toggle
## Repro steps

1. Install extension
2. Open extension's pop-up (click on extension icon)
3. Open "settings menu" by clicking "cog" icon in the top right corner
4. Click on toggle "Show Relay icon in email fields on websites"

## Expected result

The toggle changes state (goes from "ON" to "OFF")

## Actual result

Nothing happens. The toggle just gets a highlight, but does not change state.

Note that a similar toggle called "Allow Mozilla to collect interaction data" on the same page works fine.

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

File: extension/js/utils.js [hunk 1]
```diff
@@ -0,0 +1,13 @@
+/* exported areInputIconsEnabled */
+
+// eslint-disable-next-line no-redeclare
```
Comment (lesleyjanenorton) [inline extension/js/utils.js:3]: Do we still  need the `eslint-disable`?

**Review by lesleyjanenorton — APPROVED** [review]

File: extension/js/utils.js (hunk 1 above)
Comment (groovecoder) [reply extension/js/utils.js:3]: Yeah without it eslint says `'areInputIconsEnabled' is already defined as a built-in global variable. (no-redeclare)`
