### PR TITLE
Pass actual flags to <Alias>

### LINKED ISSUE #2233: The “Trackers Removed” counter from the individual email mask cards is missing
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;
- Android 11;

#### Browsers tested on:
- Firefox, Release version;
- Chrome, Release version;

#### Prerequisites:
- Be signed in into a Firefox Relay account;
- Have at least one mask created;

#### Steps to reproduce:
1. Go to the Relay dashboard;
2. Observe the individual email mask cards;

#### Expected result:
- The email mask cards should display a “Trackers Removed” counter;

#### Actual result:
- The email mask cards are missing the “Trackers Removed” counter;

#### Notes:
- This happens for both Premium and Free users;
- I was able to see the counter a single time for a newly created Premium account, but there was no counter for the total number of trackers in the header. Then, after receiving a mail with trackers removed the situation changed back and I was not able to reproduce it again;
- See attached media:
nocounter

### PR DESCRIPTION
**Pull request by Vinnl**
This PR fixes #2233 ([94add1b](https://github.com/mozilla/fx-private-relay/pull/2243/commits/94add1b0a89372b05434daea10737d8edb608269), and a similar error in [b6bb656](https://github.com/mozilla/fx-private-relay/pull/2243/commits/b6bb65653d1deb164a02f1964978841c816f7fbe), though that one didn't result in visual bugs since it's disabled anyway). I've also renamed the mocked objects to avoid accidentally importing them in non-mock context again in the future ([1350682](https://github.com/mozilla/fx-private-relay/pull/2243/commits/1350682219f6bf1801868017f90e84d324a63d65)).

How to test: with the `tracker_removal` flag enabled, you should see the count of removed trackers for individual masks.

image

- [x] l10n changes have been submitted to the l10n repository, if any.
- [ ] I've added a unit test to test for potential regressions of this bug. N/A
- [x] I've added or updated relevant docs in the docs/ directory.
- [x] All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/frontend/src/styles/tokens.scss`).
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

### CODE REVIEW

File: frontend/src/apiMocks/handlers.ts [hunk 1]
```diff
@@ -3,11 +3,11 @@ import { CustomAliasData, RandomAliasData } from "../hooks/api/aliases";
...
 import {
   mockIds,
-  domainaddresses,
-  profiles,
-  relayaddresses,
-  runtimeData,
-  users,
+  mockedDomainaddresses,
+  mockedProfiles,
+  mockedRlayaddresses,
```
Comment (maxxcrawford) [inline frontend/src/apiMocks/handlers.ts:8]: suggetion (non-blocking): Spelling 

Note: this would apply to the whole PR. 

```suggestion
  mockedRelayaddresses,
```

**Review by maxxcrawford — APPROVED** [review]
Works as expected (and I tested _without_ the flag, and it was hidden as expected too) . I found one non-blocking issue. 

Screenshot confirming working locally: 
image

File: frontend/src/apiMocks/handlers.ts (hunk 1 above)
Comment (Vinnl) [reply frontend/src/apiMocks/handlers.ts]: Haha nice catch! 71a6d438

**Comment by Vinnl** [comment]
Geez, I don't know what's happening with this PR specifically, but both Netlify and CircleCI seem to have arbitrary intermittent failures. All the force pushes are just changes to the commit message so they get retried _and_ inform GH about that...
