### PR TITLE
Show the user that subdomains will be lowercased

### LINKED ISSUE #1825: If a user tries to register a subdomain containing uppercase letters the modal doesn’t make them aware they will be changed to lowercase letters
#### Build:
- Stage;

#### Affected Platforms:
- Stage;

#### Browsers tested on:
- Firefox, Release version;
- Chrome, Release version;

#### Prerequisites:
- Be signed in into a Premium Firefox Relay account ;
- Have at least one alias created;
- Do NOT have a custom subdomain chosen;

#### Steps to reproduce:
1. Go to the Relay dashboard;
2. Click on the “Search subdomain” field and type any available name that contains uppercase letters;
3. Click on the “Search” button;
4. Observe the modal;

#### Expected result:
- The modal displays the chosen subdomain name, all letters lowercase;

#### Actual result:
- The modal displays the chosen subdomain name, letters still uppercase;

#### Notes:
- The introduced uppercase letters should be automatically changed to lowercase;
- When the user successfully registers the chosen subdomain, the uppercase letters are turned into lowercase letters anyway, so the user is informed too late that uppercase letters are not supported/allowed;
- This happens on the second step of the Premium Onboarding as well;
- See attached media:
image
image

### PR DESCRIPTION
**Pull request by Vinnl**
# New feature description

Fixes #1825.

In the preview of a user's chosen subdomain, this lowercases the chosen letters, to reflect what will happen when it's actually registered.

# Screenshot (if applicable)

image

image

image

image

# How to test

When picking a subdomain (either [in the onboarding flow](https://deploy-preview-2082--fx-relay-demo.netlify.app/?mockId=onboarding) or [the regular dashboard](https://deploy-preview-2082--fx-relay-demo.netlify.app/accounts/profile/?mockId=some)), type capital letters, then verify that it's lowercased everywhere but in the input field.

# Checklist

- [x] l10n dependencies have been merged, if any.
- [x] All acceptance criteria are met.
- [x] I've added or updated relevant docs in the docs/ directory.
- [x] All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/static/scss/libs/protocol/css/includes/tokens/dist/index.scss`).
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

### CODE REVIEW

File: frontend/__mocks__/modules/fluent__react.tsx [hunk 1]
```diff
@@ -10,12 +10,19 @@ export const mockFluentReact = {
...
+  }) =>
     isValidElement(props.children) ? (
       cloneElement(
         props.children,
         {},
-        <>[Localized with vars: {JSON.stringify(props.vars ?? {})}]</>
+        <>
+          [&lt;Localized&gt; with id [{props.id}] and vars:{" "}
+          {JSON.stringify(props.vars ?? {})}]
+        </>
```
Comment (Vinnl) [inline frontend/__mocks__/modules/fluent__react.tsx:25]: I updated the mock `<Localized>` element to also display the ID of the string that it outputs, as it was a bit hard to debug without it. Don't know why I didn't add that in the first place. (And also turned the log into `<Localized>` rather than `Localized`, to clarify that it's a component.)

File: frontend/src/components/dashboard/aliases/AliasList.tsx [hunk 2]
```diff
@@ -169,12 +169,12 @@ export const AliasList = (props: Props) => {
         </div>
         <button
           onClick={() => setStringFilterVisible(!stringFilterVisible)}
-          title={l10n.getString("banner-register-subdomain-button-search")}
+          title={l10n.getString("profile-filter-search-placeholder-2")}
```
Comment (Vinnl) [inline frontend/src/components/dashboard/aliases/AliasList.tsx:172]: This is the button to toggle the mask search field. It re-used the subdomain search label since that happened to say "Search" as well, but the context is different (possibly someone translated that as "Search subdomain"). Since the tests looks for this button label, it would get confused which search button I needed. Thus, I replaced this by the existing relevant string that said "Search masks".

image

Comment (maxxcrawford) [reply frontend/src/components/dashboard/aliases/AliasList.tsx:172]: 🦅 Catch!

**Review by lloan — APPROVED** [review]
LGTM. I tested this and it works.
