### PR TITLE
Fix #1410 - Add Mozilla VPN into Bento menu

### LINKED ISSUE #1410: Mozilla VPN not available in the Bento menu
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit

**Browsers tested on:**
Firefox

**Preconditions:**
N/A

**Steps to reproduce:**

1. Navigate to Stage server and click on the Firefox apps and services icon (Bento menu icon).
2. Observe the apps and services displayed in the menu.

**Actual result:**
Mozilla VPN is not available in the menu. 

**Expected result:**
Mozilla VPN is available in the menu. 

**Note:**
Mozilla VPN is available in the Bento menu on Monitor and Firefox Account pages.

Mozilla VPN not available

### PR DESCRIPTION
**Pull request by codemist**
This PR fixes #1410

How to test:

- [x] l10n dependencies have been merged, if any.
- [x] I've added a unit test to test for potential regressions of this bug (or this is a front-end change, where we don't yet have unit test infrastructure).
- [x] All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/static/scss/libs/protocol/css/includes/tokens/dist/index.scss`).
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

Not applicable.

# How to test

Open bento menu on both desktop and mobile. A Mozilla VPN link should be at the bottom.

# Checklist

- [x] l10n dependencies have been merged, if any.
- [x] All acceptance criteria are met.
- [x] All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/static/scss/libs/protocol/css/includes/tokens/dist/index.scss`).
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

Preview: 
image

### CODE REVIEW

File: static/js/fx-bento.js [hunk 1]
```diff
@@ -6,6 +6,7 @@ function getFxAppLinkInfo(localizedBentoStrings, referringSiteURL) {
     [localizedBentoStrings.fxPocket, "https://app.adjust.com/hr2n0yz?engagement_type=fallback_click&fallback=https%3A%2F%2Fgetpocket.com%2Ffirefox_learnmore%3Fsrc%3Dff_bento&fallback_lp=https%3A%2F%2Fapps.apple.com%2Fapp%2Fpocket-save-read-grow%2Fid309601447", "pocket"],
     [localizedBentoStrings.fxDesktop, `https://www.mozilla.org/firefox/new/?utm_source=${referringSiteURL}&utm_medium=referral&utm_campaign=bento&utm_content=desktop`, "fx-desktop"],
     [localizedBentoStrings.fxMobile, `http://mozilla.org/firefox/mobile?utm_source=${referringSiteURL}&utm_medium=referral&utm_campaign=bento&utm_content=desktop`, "fx-mobile"],
+    [localizedBentoStrings.fxVPN, `http://mozilla.org/firefox/mobile?utm_source=${referringSiteURL}&utm_medium=referral&utm_campaign=bento&utm_content=desktop`, "fx-vpn"],
```
Comment (Vinnl) [inline static/js/fx-bento.js:9]: I assume this link will need to point to the actual VPN website, rather than the Firefox Mobile website? :)

File: privaterelay/templates/includes/header.html [hunk 2]
```diff
@@ -97,5 +97,5 @@
       {% endif %}
     </div>
   </nav>
-  <fluent class="bento-strings" data-bento-button-title="{% ftlmsg 'bento-button-title' %}" data-fx-makes-tech="{% ftlmsg 'fx-makes-tech' %}" data-made-by-mozilla="{% ftlmsg 'made-by-mozilla' %}" data-fx-desktop="{% ftlmsg 'fx-desktop' %}" data-fx-lockwise="{% ftlmsg 'fx-lockwise' %}" data-fx-mobile="{% ftlmsg 'fx-mobile' %}" data-fx-monitor="{% ftlmsg 'fx-monitor' %}" data-fx-pocket="{% ftlmsg 'fx-pocket' %}" data-bento-button-close-label="{% ftlmsg 'bento-button-close-label' %}"></fluent>
+  <fluent class="bento-strings" data-bento-button-title="{% ftlmsg 'bento-button-title' %}" data-fx-makes-tech="{% ftlmsg 'fx-makes-tech' %}" data-made-by-mozilla="{% ftlmsg 'made-by-mozilla' %}" data-fx-desktop="{% ftlmsg 'fx-desktop' %}" data-fx-lockwise="{% ftlmsg 'fx-lockwise' %}" data-fx-mobile="{% ftlmsg 'fx-mobile' %}" data-fx-monitor="{% ftlmsg 'fx-monitor' %}" data-fx-pocket="{% ftlmsg 'fx-pocket' %}" data-fx-vpn="Mozilla VPN" data-bento-button-close-label="{% ftlmsg 'bento-button-close-label' %}"></fluent>
```
Comment (Vinnl) [inline privaterelay/templates/includes/header.html:100]: I don't think product names are usually translated, but since the other product names were added to the Fluent files, maybe this one would need to be too?

Comment (Vinnl) [reply privaterelay/templates/includes/header.html:100]: Ah, I see that's because https://github.com/mozilla-l10n/fx-private-relay-l10n/pull/51 isn't merged yet :)

File: static/js/fx-bento.js (hunk 1 above)
Comment (codemist) [reply static/js/fx-bento.js:9]: Yep, blocking this for now since I need https://github.com/mozilla-l10n/fx-private-relay-l10n/pull/51 merged in first.

**Comment by codemist** [comment]
@maxxcrawford I'm not super familiar with how the bento js was written, but I can't seem to be able to add the string into the new Mozilla VPN link.

File: static/js/fx-bento.js [hunk 3]
```diff
@@ -6,6 +6,7 @@ function getFxAppLinkInfo(localizedBentoStrings, referringSiteURL) {
     [localizedBentoStrings.fxPocket, "https://app.adjust.com/hr2n0yz?engagement_type=fallback_click&fallback=https%3A%2F%2Fgetpocket.com%2Ffirefox_learnmore%3Fsrc%3Dff_bento&fallback_lp=https%3A%2F%2Fapps.apple.com%2Fapp%2Fpocket-save-read-grow%2Fid309601447", "pocket"],
     [localizedBentoStrings.fxDesktop, `https://www.mozilla.org/firefox/new/?utm_source=${referringSiteURL}&utm_medium=referral&utm_campaign=bento&utm_content=desktop`, "fx-desktop"],
     [localizedBentoStrings.fxMobile, `http://mozilla.org/firefox/mobile?utm_source=${referringSiteURL}&utm_medium=referral&utm_campaign=bento&utm_content=desktop`, "fx-mobile"],
+    [localizedBentoStrings.fxVPN, `https://www.mozilla.org/en-US/products/vpn/`, "fx-vpn"],
```
Comment (maxxcrawford) [inline static/js/fx-bento.js:9]: Note there's two changes here: 

- Revise the casing to `fxVpn`
- Adjust the URL to include the same tracking information that the other mozilla.org sites have (and also remove the en-US locale specificity) . 

```suggestion
    [localizedBentoStrings.fxVpn, `https://www.mozilla.org/products/vpn/?utm_source=${referringSiteURL}&utm_medium=referral&utm_campaign=bento&utm_content=desktop`, "fx-vpn"],
```

File: static/js/fx-bento.js [hunk 4]
```diff
@@ -32,6 +33,7 @@ async function getlocalizedBentoStrings() {
       "fxMobile":"Firefox Browser for Mobile",
       "fxMonitor":"Firefox Monitor",
       "fxPocket":"Pocket",
+      "fxVPN":"Mozilla VPN",
```
Comment (maxxcrawford) [inline static/js/fx-bento.js:36]: Revise the data element ID to be camelCase.

```suggestion
      "fxVpn":"Mozilla VPN",
```

File: static/scss/partials/fx-bento.scss [hunk 5]
```diff
@@ -165,6 +165,10 @@ a.fx-bento-app-link {
     background-position-x: -18px;
 }
 
+.fx-bento-app-link-span.fx-vpn::before {
+    background-position-x: -162.5px;
```
Comment (maxxcrawford) [inline static/scss/partials/fx-bento.scss:169]: If it's possible to adjust this from a `.5px` to a whole pixel, let's do so. This may be my old browser-compat quirks showing but half-pixels can render strangely sometimes.

**Review by maxxcrawford — CHANGES_REQUESTED** [review]
I found the culprit — camelCasing! ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset)) You have to use it when selecting `dataset` items in JavaScript.  The `VPN` all-caps casing was throwing everything off.

File: static/js/fx-bento.js (hunk 3 above)
Comment (codemist) [reply static/js/fx-bento.js]: Ooh, got it. Thanks!

File: static/js/fx-bento.js (hunk 4 above)
Comment (codemist) [reply static/js/fx-bento.js]: I've changed all instances of `VPN` to `Vpn`.

File: static/scss/partials/fx-bento.scss (hunk 5 above)
Comment (codemist) [reply static/scss/partials/fx-bento.scss]: Got it, half pixel is removed.

File: static/js/fx-bento.js [hunk 6]
```diff
@@ -6,6 +6,7 @@ function getFxAppLinkInfo(localizedBentoStrings, referringSiteURL) {
     [localizedBentoStrings.fxPocket, "https://app.adjust.com/hr2n0yz?engagement_type=fallback_click&fallback=https%3A%2F%2Fgetpocket.com%2Ffirefox_learnmore%3Fsrc%3Dff_bento&fallback_lp=https%3A%2F%2Fapps.apple.com%2Fapp%2Fpocket-save-read-grow%2Fid309601447", "pocket"],
     [localizedBentoStrings.fxDesktop, `https://www.mozilla.org/firefox/new/?utm_source=${referringSiteURL}&utm_medium=referral&utm_campaign=bento&utm_content=desktop`, "fx-desktop"],
     [localizedBentoStrings.fxMobile, `http://mozilla.org/firefox/mobile?utm_source=${referringSiteURL}&utm_medium=referral&utm_campaign=bento&utm_content=desktop`, "fx-mobile"],
+    [localizedBentoStrings.fxVpn, "https://www.mozilla.org/en-US/products/vpn/", "fx-vpn"],
```
Comment (pdehaan) [inline static/js/fx-bento.js:9]: Nit: take out /en-US/ path from url and let mozilla.org redirect to best locale.

Comment (codemist) [reply static/js/fx-bento.js]: Done!

File: static/js/fx-bento.js (hunk 3 above)
Comment (maxxcrawford) [reply static/js/fx-bento.js]: Can you include this UTM change? I'm good after that.

File: static/js/fx-bento.js [hunk 7]
```diff
@@ -6,6 +6,7 @@ function getFxAppLinkInfo(localizedBentoStrings, referringSiteURL) {
     [localizedBentoStrings.fxPocket, "https://app.adjust.com/hr2n0yz?engagement_type=fallback_click&fallback=https%3A%2F%2Fgetpocket.com%2Ffirefox_learnmore%3Fsrc%3Dff_bento&fallback_lp=https%3A%2F%2Fapps.apple.com%2Fapp%2Fpocket-save-read-grow%2Fid309601447", "pocket"],
     [localizedBentoStrings.fxDesktop, `https://www.mozilla.org/firefox/new/?utm_source=${referringSiteURL}&utm_medium=referral&utm_campaign=bento&utm_content=desktop`, "fx-desktop"],
     [localizedBentoStrings.fxMobile, `http://mozilla.org/firefox/mobile?utm_source=${referringSiteURL}&utm_medium=referral&utm_campaign=bento&utm_content=desktop`, "fx-mobile"],
+    [localizedBentoStrings.fxVpn, "https://www.mozilla.org/products/vpn/", "fx-vpn"],
```
Comment (maxxcrawford) [inline static/js/fx-bento.js:9]: Resubmitting this request again as it is still outstanding. We need to add UTM params: 

```suggestion
    [localizedBentoStrings.fxVpn, "https://www.mozilla.org/products/vpn?utm_source=${referringSiteURL}&utm_medium=referral&utm_campaign=bento&utm_content=desktop/", "fx-vpn"],
```

**Review by maxxcrawford — DISMISSED** [review]
We are still missing UTM params to the VPN link. Please add and this will be good to go.

File: static/js/fx-bento.js (hunk 7 above)
Comment (codemist) [reply static/js/fx-bento.js:9]: Should I add one for monitor as well? It's currently only `https://monitor.firefox.com/` on L5

Comment (codemist) [reply static/js/fx-bento.js]: Added UTM params for monitor and VPN.

File: static/js/fx-bento.js [hunk 8]
```diff
@@ -2,10 +2,11 @@
 
 function getFxAppLinkInfo(localizedBentoStrings, referringSiteURL) {
   return [
-    [localizedBentoStrings.fxMonitor, "https://monitor.firefox.com/", "fx-monitor"],
+    [localizedBentoStrings.fxMonitor, "https://monitor.firefox.com/?utm_source=www.mozilla.org&amp;utm_medium=referral&amp;utm_campaign=nav&amp;utm_content=products", "fx-monitor"],
```
Comment (Vinnl) [inline static/js/fx-bento.js:5]: We'll probably want to align this with the other UTM parameters?

```suggestion
    [localizedBentoStrings.fxMonitor, "https://monitor.firefox.com/?utm_source=${referringSiteURL}&amp;utm_medium=referral&amp;utm_campaign=bento&amp;utm_content=desktop", "fx-monitor"],
```

File: static/js/fx-bento.js [hunk 9]
```diff
@@ -2,10 +2,11 @@
...
     [localizedBentoStrings.fxPocket, "https://app.adjust.com/hr2n0yz?engagement_type=fallback_click&fallback=https%3A%2F%2Fgetpocket.com%2Ffirefox_learnmore%3Fsrc%3Dff_bento&fallback_lp=https%3A%2F%2Fapps.apple.com%2Fapp%2Fpocket-save-read-grow%2Fid309601447", "pocket"],
     [localizedBentoStrings.fxDesktop, `https://www.mozilla.org/firefox/new/?utm_source=${referringSiteURL}&utm_medium=referral&utm_campaign=bento&utm_content=desktop`, "fx-desktop"],
     [localizedBentoStrings.fxMobile, `http://mozilla.org/firefox/mobile?utm_source=${referringSiteURL}&utm_medium=referral&utm_campaign=bento&utm_content=desktop`, "fx-mobile"],
+    [localizedBentoStrings.fxVpn, "https://www.mozilla.org/products/vpn?utm_source=${referringSiteURL}&utm_medium=referral&utm_campaign=bento&utm_content=desktop/", "fx-vpn"],
```
Comment (Vinnl) [inline static/js/fx-bento.js:9]: I think this trailing slash might carry over to Google Analytics.

```suggestion
    [localizedBentoStrings.fxVpn, "https://www.mozilla.org/products/vpn?utm_source=${referringSiteURL}&utm_medium=referral&utm_campaign=bento&utm_content=desktop", "fx-vpn"],
```

**Review by Vinnl — APPROVED** [review]
UTM parameteres still don't look quite correct, but I added suggestions that should make them as they should.

File: static/js/fx-bento.js (hunk 8 above)
Comment (codemist) [reply static/js/fx-bento.js:5]: Ah yes, good call

**Comment by pdehaan** [comment]
One day I might need somebody to explain the "bento" concept to me (and where it's used).
But currently it looks like each of the 3 Bento menus I know of on The Web all show different links/products.

Off the top of my head&hellip;

| SITE | SCREENSHOT | NOTES |
|:----|:----|:----|
| [Private Relay](https://relay.firefox.com/) | Screen Shot 2022-02-03 at 9 46 20 AM | No VPN (Added in this PR but not on prod yet)<br/>No Relay
| [Firefox Monitor](https://monitor.firefox.com/) | Screen Shot 2022-02-03 at 9 45 14 AM | Has VPN<br/>No Relay
| [Firefox Accounts](https://accounts.firefox.com/settings) | Screen Shot 2022-02-03 at 9 47 11 AM | Has VPN and Relay
| [Firefox VPN](https://www.mozilla.org/products/vpn/) | n/a | No bento, but it's mozilla.org, so maybe that's a consistency thing.

Not sure if it'd be possible/easy to make a reusable "bento" component that could be localized and shared among projects, or if that'd just lead to UTM attribution nightmares if we're tracking referrers, etc.
