### PR TITLE
Only hide add-on banner with the add-on installed

### LINKED ISSUE #868: The banner section disappears after installing the dev version of the Relay addon
#### Platforms affected::
- Windows 10, Linux Ubuntu 18.04, MacOS 10.15;

#### Browsers tested on:
- Firefox;

#### Prerequisites:
- A new firefox profile has been created;
- The user has a Private Relay account without the Mozilla Privacy Pack purchased;
- Have the test addon downloaded, but not installed;

#### Steps to reproduce:
1. Open firefox in the new profile;
2. Go to https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/;
3. Log into the created profile and check the banner section just below the page header;
4. Install the test addon that points to the fxa stage;
5. Refresh the Relay page and check the banner section again;

#### Expected result:
- The promotional banner should stay displayed;

#### Actual result:
- The promotional banner disappears;

#### Notes:
- Uninstalling the extension and refreshing does not change anything;

image
image

### LINKED ISSUE #935: Installing the stage version of Private Relay Add-on makes the “Get your domain name” banner disappear
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Be signed in into a Firefox Relay account with an active subscription;

#### Steps to reproduce:
1. Go to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/ ;
2. Install the stage version of the Relay Add-on;
3. Observe the changes;

#### Expected result:
- The page updates accordingly, the banner that suggests the user to install the Reay add-on disappearing;

#### Actual result:
- The “Get your domain name” banner disappears;

#### Notes:
- Similar to issue [868](https://github.com/mozilla/fx-private-relay/issues/868) ;

domain1 2
domain1 3

### PR DESCRIPTION
**Pull request by Vinnl**
Fixes #868, fixes #935.

This required a bit of code archeology, so I'm not sure if I
correctly interpreted the original intentions of the code, but it
seems like we used to only have a banner suggesting the
installation of the add-on, which then got updated to hide
.dashboard-banners when the add-on was installed. Over time, more
banners were added ("download Firefox", "upgrade to Premium"), but
those were all stashed inside .dashboard-banners, which got
hidden when the add-on was installed. Additionally, it seems the
banners are supposed to appear on the page a little bit after page
load? Or maybe that is to give the add-on time to load.

Either way, I now opted to revert the code that hides
.dashboard-banners if the add-on is installed (and thus now only
makes it appear after a delay of half a second). Instead, the
add-on banner specifically is hidden using CSS only, using a
selector that only matches when the add-on has set
`data-addon-installed` to true in `<firefox-private-relay-addon>`.

### CODE REVIEW

File: static/js/app.js [hunk 1]
```diff
@@ -312,11 +309,9 @@ function showBannersIfNecessary() {
   const bg = dashboardBanners.querySelector(".banner-gradient-bg");
   const showBanner = (bannerEl) => {
     setTimeout(()=> {
-      if (!isRelayAddonInstalled()) {
-        bg.style.minHeight = "101px";
-        bannerEl.classList.remove("hidden");
-        dashboardBanners.classList.remove("invisible");
-      }
+      bg.style.minHeight = "101px";
```
Comment (maxxcrawford) [inline static/js/app.js:312]: I believe this `min-height` bit of code is super legacy and can be removed. We migrated to a `display: sticky` layout for the header a few releases ago, making this not as necessary.

**Review by maxxcrawford — APPROVED** [review]
Looks good. I think there's some more code that can actually be removed (or at least migrated over to CSS). I'm marking it as non-blocking, if you want to proceed. Merge at your convenience.

File: static/js/app.js (hunk 1 above)
Comment (Vinnl) [reply static/js/app.js]: 48d127a
